### ISSUE TITLE
How to send the token to greeting?

### ISSUE THREAD

**Issue by christian04** [gk1github/SpringRestSecurityToken#1]
Hello,
I could log on and to give me the Token , but I could not send the Token **"/api/greeting**" .
Please could you explain how it sent the token.

Regards

**Comment by ramachandrann** [comment]
Once you receive the token on logon, you must use the token in http header Authorization Bearer. e.g. http://stackoverflow.com/questions/22229996/basic-http-and-bearer-token-authentication

**Comment by ramachandrann** [comment]
closing issue.

**Comment by christian04** [comment]
Hello,

I tried to make an example with jquery ajax from adding the parameter header token but I still sending a 403.

I also tested with SoapUI sending the token in the header, but it's sending a 403.

Regards

**Comment by ramachandrann** [comment]
pls send in a bare bores ready-to-test UI that can help me debug this issue.
